### ISSUE TITLE
error with scrape data

### ISSUE THREAD

**Issue by johnfelipe** [crestonbunch/neural-namer#2]
```
(venv) root@ubuntu20portatil:~/neural-namer# crawl wikia --out crawler/wikia/data/names.csv
Traceback (most recent call last):
  File "/root/neural-namer/venv/bin/crawl", line 11, in <module>
    load_entry_point('neural-namer', 'console_scripts', 'crawl')()
  File "/root/neural-namer/crawler/commands.py", line 32, in main
    fetch_func(args.out)
  File "/root/neural-namer/crawler/wikia/commands.py", line 23, in fetch
    with open(outfile, 'w') as file_handler:
FileNotFoundError: [Errno 2] No such file or directory: 'crawler/wikia/data/names.csv'

```

**Comment by johnfelipe** [comment]
anyone?
